# Generated by Django 4.2.7 on 2025-11-22 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_message_read_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="pastor",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected pastor for the service",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="officiated_bookings",
                to="core.churchstaff",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="submitted_form",
            field=models.FileField(
                blank=True,
                help_text="Filled form submitted by user",
                null=True,
                upload_to="bookings/forms/",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(blank=True, help_text="Requested date", null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("reviewed", "Reviewed"),
                    ("approved", "Approved"),
                    ("completed", "Completed"),
                    ("declined", "Declined"),
                    ("canceled", "Canceled"),
                    ("inquiry", "Inquiry/Form Requested"),
                    ("forms_submitted", "Forms Submitted"),
                    ("pre_approved", "Pre-Approved (Proceedings Done)"),
                    ("pastor_selected", "Pastor Selected"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="churchstaff",
            name="role",
            field=models.CharField(
                choices=[
                    ("secretary", "Parish Secretary/Coordinator"),
                    ("volunteer", "Ministry Leader/Volunteer"),
                    ("pastor", "Parish Priest/Pastor"),
                ],
                help_text="Staff role in the parish",
                max_length=20,
            ),
        ),
    ]
