# Generated by Django 4.2.7 on 2026-02-03 05:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_booking_pastor_booking_submitted_form_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="submitted_form",
        ),
        migrations.AddField(
            model_name="bookableservice",
            name="requirements",
            field=models.TextField(
                blank=True, help_text="List of requirements needed for this service"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="form_approval_notes",
            field=models.TextField(
                blank=True, help_text="Notes from parish when approving/processing form"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="form_documents",
            field=models.TextField(
                blank=True, help_text="JSON or text describing submitted documents"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="form_provided_at",
            field=models.DateTimeField(
                blank=True, help_text="When the parish provided the form", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="form_request_notes",
            field=models.TextField(
                blank=True, help_text="Initial notes when requesting the form"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="form_submitted_at",
            field=models.DateTimeField(
                blank=True, help_text="When user submitted the filled form", null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Scheduled date (set after form approval)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(
                blank=True, help_text="Scheduled end time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True, help_text="Additional notes"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.TimeField(
                blank=True, help_text="Scheduled start time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("form_requested", "Form Requested"),
                    ("form_provided", "Form Provided by Parish"),
                    ("form_submitted", "Form Submitted"),
                    ("form_processing", "Processing Form"),
                    ("form_approved", "Form Approved"),
                    ("pending_requirements", "Pending Requirements"),
                    ("ready_to_schedule", "Ready to Schedule"),
                    ("pastor_selection", "Select Pastor"),
                    ("pastor_assigned", "Pastor Assigned"),
                    ("scheduling", "Schedule Date"),
                    ("scheduled", "Date Scheduled"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("requested", "Requested"),
                    ("reviewed", "Reviewed"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("canceled", "Canceled"),
                ],
                default="form_requested",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="churchstaff",
            name="role",
            field=models.CharField(
                choices=[
                    ("secretary", "Parish Secretary/Coordinator"),
                    ("volunteer", "Ministry Leader/Volunteer"),
                ],
                help_text="Staff role in the parish",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Pastor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Pastor's full name", max_length=200),
                ),
                (
                    "title",
                    models.CharField(
                        default="Rev. Fr.",
                        help_text="Title (e.g., Rev. Fr., Deacon, Minister)",
                        max_length=100,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Pastor's email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Pastor's phone number",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Enter a valid phone number."
                            )
                        ],
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Pastor's photo",
                        null=True,
                        upload_to="pastors/photos/",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Brief biography or description"
                    ),
                ),
                (
                    "specializations",
                    models.TextField(
                        blank=True,
                        help_text="Specializations or services they handle (e.g., Baptism, Wedding, Counseling)",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this pastor is currently available for bookings",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (0 = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastors",
                        to="core.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pastor",
                "verbose_name_plural": "Pastors",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="pastor",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned pastor for this service",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="core.pastor",
            ),
        ),
    ]
