# Generated by Django 4.2.7 on 2026-02-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_remove_booking_submitted_form_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastor",
            name="available_days",
            field=models.CharField(
                default="0,1,2,3,4,5,6",
                help_text="Comma-separated days of week (0=Mon, 6=Sun) when available",
                max_length=20,
            ),
        ),
    ]
