# Generated by Django 4.2.7 on 2026-02-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_booking_event_date_booking_event_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("form_requested", "Form Requested"),
                    ("form_provided", "Form Provided by Parish"),
                    ("form_submitted", "Form Submitted"),
                    ("form_processing", "Processing Form"),
                    ("form_approved", "Form Approved"),
                    ("pending_requirements", "Pending Requirements"),
                    ("ready_to_schedule", "Ready to Schedule"),
                    ("pastor_selection", "Select Pastor"),
                    ("pastor_assigned", "Pastor Assigned"),
                    ("scheduling", "Schedule Date"),
                    ("schedule_requested", "Schedule Requested"),
                    ("scheduled", "Interview Scheduled"),
                    ("interview_completed", "Interview Completed"),
                    ("event_scheduled", "Event Scheduled"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("requested", "Requested"),
                    ("reviewed", "Reviewed"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("canceled", "Canceled"),
                ],
                default="form_requested",
                max_length=30,
            ),
        ),
    ]
