# Generated by Django 4.2.7 on 2026-02-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_add_event_preparation_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastor",
            name="preparation_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Number of days the priest needs to prepare before an event",
            ),
        ),
    ]
