# Generated by Django 4.2.7 on 2026-02-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_add_pastor_preparation_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookableservice",
            name="available_time_slots",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated time slots (e.g., 9:00 AM - 11:00 AM, 1:00 PM - 4:00 PM)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="pastor",
            name="available_time_slots",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated time slots (e.g., 9:00 AM - 11:00 AM, 1:00 PM - 4:00 PM)",
                max_length=500,
            ),
        ),
    ]
