# Generated by Django 4.2.7 on 2026-02-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_bookableservice_available_time_slots_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="event_time_slot",
            field=models.CharField(
                blank=True,
                help_text="Selected event time slot",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="time_slot",
            field=models.CharField(
                blank=True,
                help_text="Selected time slot (e.g., 1pm - 4pm)",
                max_length=100,
                null=True,
            ),
        ),
    ]
